/**
 * `@truocloud/img` — URL builder for img.truo.cloud.
 *
 * **Zero dependencies, no crypto.** Signing lives behind a second entrypoint
 * (`@truocloud/img/sign`) so a bundler never drags `node:crypto` — or your
 * signing secret — into browser code. If someone does import it in a client
 * bundle, the build breaks loudly, which is the point.
 *
 * ```ts
 * import { createTruoImg } from "@truocloud/img";
 *
 * const img = createTruoImg({ pid: "acme" });
 * img.url("uploads/photo.jpg", { width: 800, format: "auto" });
 * img.srcset("uploads/photo.jpg", { transform: { format: "auto" } });
 * ```
 *
 * Every rule this package implements is pinned by `fixtures/urls.json`, which is
 * generated by the service and also consumed by the WordPress plugin's PHP
 * builder. When they disagree, the fixture is right.
 */
import { buildUrl } from "./build.ts";
import type { Transform, TruoImgConfig } from "./config.ts";
import { lqip, lqipDataUrl, sizes, srcset, type LqipOptions, type SrcsetOptions } from "./srcset.ts";

export { buildUrl, buildQuery, DEFAULT_BASE_URL } from "./build.ts";
export { parseUrl, type ParsedUrl } from "./parse.ts";
export { srcset, sizes, lqip, lqipDataUrl, resolveWidths } from "./srcset.ts";
export { canonicalName, CANONICAL_NAMES } from "./names.ts";
export {
  DEFAULT_WIDTHS,
  DEFAULT_MAX_WIDTH,
  type TruoImgConfig,
  type Transform,
} from "./config.ts";
export type { SrcsetOptions, LqipOptions } from "./srcset.ts";

export interface TruoImg {
  readonly config: TruoImgConfig;
  url(src: string, transform?: Transform): string;
  srcset(src: string, opts?: SrcsetOptions): string;
  sizes(breakpoints: Array<[number, string]>, fallback?: string): string;
  lqip(src: string, opts?: LqipOptions): string;
  lqipDataUrl(src: string, opts?: LqipOptions): Promise<string>;
}

/**
 * Binds the configuration once.
 *
 * This is the shape every loader uses: a framework loader is handed a `src` and
 * a `width` and nothing else, so the pid and the origin have to be closed over
 * somewhere.
 */
export function createTruoImg(config: TruoImgConfig): TruoImg {
  if (!config?.pid) throw new Error("@truocloud/img: `pid` is required");
  return {
    config,
    url: (src, transform) => buildUrl(src, transform, config),
    srcset: (src, opts) => srcset(src, opts, config),
    sizes,
    lqip: (src, opts) => lqip(src, opts, config),
    lqipDataUrl: (src, opts) => lqipDataUrl(src, opts, config),
  };
}
