/**
 * JSON Schema → TypeScript.
 *
 * Written by hand instead of using `openapi-typescript` for a concrete reason: the spec
 * is generated by Zod, so the subset of JSON Schema that shows up here is small and
 * well-known, and in exchange the whole devkit stays **without build dependencies**. A
 * client can clone, run `bun run gen` and get the SDK without installing anything. If
 * someday the spec picks up constructs this does not cover, `unsupportedSchema()` shouts
 * instead of silently emitting `any` — which is how a type generator lies to you.
 */
import type { JsonSchema } from "../../openapi/src/index.ts";
import { jsdoc, quoteKey } from "./util.ts";

export interface EmitCtx {
  /** Names from `components.schemas`, to resolve `$ref`. */
  known: Set<string>;
  /** Refs actually used, to be able to warn about orphaned schemas. */
  used: Set<string>;
}

export function refName(ref: string): string {
  const m = /^#\/components\/schemas\/(.+)$/.exec(ref);
  if (!m) throw new Error(`Unsupported $ref: ${ref} (only #/components/schemas/*)`);
  return m[1]!;
}

function lit(v: unknown): string {
  if (v === null) return "null";
  if (typeof v === "string") return JSON.stringify(v);
  if (typeof v === "number" || typeof v === "boolean") return String(v);
  return "unknown";
}

function primitive(t: string): string {
  switch (t) {
    case "string":
      return "string";
    case "number":
    case "integer":
      return "number";
    case "boolean":
      return "boolean";
    case "null":
      return "null";
    case "object":
      return "Record<string, unknown>";
    case "array":
      return "unknown[]";
    default:
      return "unknown";
  }
}

function union(parts: string[]): string {
  const uniq = [...new Set(parts)];
  if (uniq.length === 0) return "never";
  if (uniq.length === 1) return uniq[0]!;
  return uniq.map((p) => (p.includes("=>") || p.includes("|") ? `(${p})` : p)).join(" | ");
}

/**
 * Type expression for a schema. `indent` only affects the pretty-printing of inline
 * objects; `$ref`s and primitives ignore it.
 */
export function tsType(schema: JsonSchema | undefined | null, ctx: EmitCtx, indent = ""): string {
  if (!schema) return "unknown";

  if (schema.$ref) {
    const name = refName(schema.$ref);
    if (!ctx.known.has(name)) throw new Error(`$ref to a nonexistent schema: ${name}`);
    ctx.used.add(name);
    return name;
  }

  if (schema.const !== undefined) return lit(schema.const);

  if (schema.enum) {
    const base = union(schema.enum.map(lit));
    return schema.nullable ? union([base, "null"]) : base;
  }

  if (schema.allOf?.length) {
    const parts = schema.allOf.map((s) => tsType(s, ctx, indent));
    return parts.length === 1 ? parts[0]! : parts.join(" & ");
  }

  const variants = schema.oneOf ?? schema.anyOf;
  if (variants?.length) {
    const u = union(variants.map((s) => tsType(s, ctx, indent)));
    return schema.nullable ? union([u, "null"]) : u;
  }

  // `type` can be an array (OpenAPI 3.1): `["string","null"]`.
  const types = Array.isArray(schema.type) ? schema.type : schema.type ? [schema.type] : [];

  if (types.length === 0) {
    // No `type` but with `properties` is still an object; otherwise, it is free-form.
    if (schema.properties) return objectType(schema, ctx, indent);
    return "unknown";
  }

  const parts = types.map((t) => {
    if (t === "object") return objectType(schema, ctx, indent);
    if (t === "array") return arrayType(schema, ctx, indent);
    return primitive(t);
  });

  return schema.nullable ? union([...parts, "null"]) : union(parts);
}

function arrayType(schema: JsonSchema, ctx: EmitCtx, indent: string): string {
  const inner = tsType(schema.items, ctx, indent);
  return /[|&\s]/.test(inner) && !inner.endsWith("]") ? `(${inner})[]` : `${inner}[]`;
}

function objectType(schema: JsonSchema, ctx: EmitCtx, indent: string): string {
  const props = schema.properties;
  if (!props || Object.keys(props).length === 0) {
    const ap = schema.additionalProperties;
    if (ap && typeof ap === "object") return `Record<string, ${tsType(ap, ctx, indent)}>`;
    return "Record<string, unknown>";
  }
  const req = new Set(schema.required ?? []);
  const inner = indent + "  ";
  const lines: string[] = [];
  for (const [key, value] of Object.entries(props)) {
    const doc = jsdoc(value.description, inner);
    const optional = req.has(key) ? "" : "?";
    lines.push(`${doc}${inner}${quoteKey(key)}${optional}: ${tsType(value, ctx, inner)};`);
  }
  const extra =
    schema.additionalProperties && typeof schema.additionalProperties === "object"
      ? `\n${inner}[key: string]: ${tsType(schema.additionalProperties, ctx, inner)};`
      : "";
  return `{\n${lines.join("\n")}${extra}\n${indent}}`;
}

/** `export type X = …` declaration for a named schema from `components.schemas`. */
export function declareSchema(name: string, schema: JsonSchema, ctx: EmitCtx): string {
  const doc = jsdoc(schema.description);
  return `${doc}export type ${name} = ${tsType(schema, ctx, "")};\n`;
}
