/**
 * Generates the parameter table for the Images docs from the shared fixture.
 *
 * Same rule as the API reference: what describes an interface is generated, not
 * written. A hand-kept table of ~40 parameters and their aliases is a table that
 * is wrong within two releases, and the failure is quiet — a reader writes a
 * parameter that no longer exists, the service ignores it, and the image comes
 * back untransformed with a 200.
 *
 *   bun scripts/generate-images.ts
 *
 * Output: src/content/docs/images/_parameters.md (partial, imported by url.mdx)
 */
const FIXTURE = new URL("../../img/fixtures/urls.json", import.meta.url);
const TARGET = new URL("../src/content/docs/images/_parameters.md", import.meta.url);

const fixture = (await Bun.file(FIXTURE).json()) as {
  canonical_names: Record<string, string>;
};

// Group the public names by the canonical one they resolve to.
const byCanonical = new Map<string, string[]>();
for (const [alias, canonical] of Object.entries(fixture.canonical_names)) {
  if (alias === canonical) continue;
  byCanonical.set(canonical, [...(byCanonical.get(canonical) ?? []), alias]);
}

const rows = [...new Set(Object.values(fixture.canonical_names))]
  .sort()
  .map((canonical) => {
    const aliases = (byCanonical.get(canonical) ?? []).sort();
    return `| \`${canonical}\` | ${aliases.length ? aliases.map((a) => `\`${a}\``).join(", ") : "—"} |`;
  });

const body = `<!-- GENERATED by docs/scripts/generate-images.ts from the shared URL fixture. Do not edit. -->

| Parameter | Also accepted as |
| --- | --- |
${rows.join("\n")}
`;

await Bun.write(TARGET, body);
console.log(`[images] ${rows.length} parameters -> ${TARGET.pathname}`);
