/**
 * Generates the Homebrew formula and the Scoop manifest for a version.
 *
 *   bun scripts/packagers.ts 0.2.0
 *
 * Both point at the binaries of the GitHub release and verify the sha256 produced by
 * `bun run build --binaries` (the `SHA256SUMS` file). They are generated rather than
 * written by hand because a hand-typed hash is wrong half the time, and the symptom is a
 * `brew install` that fails after downloading 60 MB.
 *
 * Output goes to `dist-packagers/`; the workflow pushes them to `truocloud/homebrew-tap`
 * and `truocloud/scoop-bucket`.
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const ROOT = resolve(import.meta.dirname, "..");
const BIN = resolve(ROOT, "packages/cli/bin");
const OUT = resolve(ROOT, "dist-packagers");

const version = (process.argv[2] ?? "").replace(/^v/, "");
if (!/^\d+\.\d+\.\d+(-[0-9A-Za-z.-]+)?$/.test(version)) {
  console.error("Usage: bun scripts/packagers.ts <version>");
  process.exit(2);
}

const REPO = "truocloud/truo-devkit";
const base = `https://github.com/${REPO}/releases/download/v${version}`;

/** `<sha256>  <file>` → map. This is the `sha256sum` format. */
function readChecksums(): Map<string, string> {
  const text = readFileSync(resolve(BIN, "SHA256SUMS"), "utf8");
  const map = new Map<string, string>();
  for (const line of text.split("\n")) {
    const match = /^([0-9a-f]{64})\s+(\S+)$/.exec(line.trim());
    if (match) map.set(match[2]!, match[1]!);
  }
  return map;
}

const sums = readChecksums();
function sha(file: string): string {
  const value = sums.get(file);
  // Better to break the release than publish a formula that verifies nothing:
  // an empty `sha256 ""` in brew installs anyway, without checking.
  if (!value) throw new Error(`missing sha256 for ${file} in SHA256SUMS`);
  return value;
}

mkdirSync(OUT, { recursive: true });

// ── Homebrew ────────────────────────────────────────────────────────────────
// A binary, not `depends_on "node"`: the whole point of single-file is that installing
// the CLI does not drag in a runtime. `brew install truocloud/tap/truo`.
const formula = `# Generated by scripts/packagers.ts — do not edit by hand.
class Truo < Formula
  desc "TruoCloud CLI: VPS, DNS, databases, containers and load balancers"
  homepage "https://docs.truo.cloud/cli"
  version "${version}"
  license "MIT"

  on_macos do
    on_arm do
      url "${base}/truo-darwin-arm64"
      sha256 "${sha("truo-darwin-arm64")}"
    end
    on_intel do
      url "${base}/truo-darwin-x64"
      sha256 "${sha("truo-darwin-x64")}"
    end
  end

  on_linux do
    on_arm do
      url "${base}/truo-linux-arm64"
      sha256 "${sha("truo-linux-arm64")}"
    end
    on_intel do
      url "${base}/truo-linux-x64"
      sha256 "${sha("truo-linux-x64")}"
    end
  end

  def install
    bin.install Dir["truo-*"].first => "truo"
    generate_completions_from_executable(bin/"truo", "completion", shells: [:bash, :zsh, :fish])
  end

  test do
    assert_match "${version}", shell_output("#{bin}/truo --version")
  end
end
`;
writeFileSync(resolve(OUT, "truo.rb"), formula, "utf8");

// ── Scoop ───────────────────────────────────────────────────────────────────
// `scoop bucket add truocloud https://github.com/truocloud/scoop-bucket`
const manifest = {
  version,
  description: "TruoCloud CLI: VPS, DNS, databases, containers and load balancers",
  homepage: "https://docs.truo.cloud/cli",
  license: "MIT",
  architecture: {
    "64bit": {
      url: `${base}/truo-windows-x64.exe#/truo.exe`,
      hash: sha("truo-windows-x64.exe"),
    },
  },
  bin: "truo.exe",
  checkver: {
    github: `https://github.com/${REPO}`,
  },
  autoupdate: {
    architecture: {
      "64bit": {
        url: `https://github.com/${REPO}/releases/download/v$version/truo-windows-x64.exe#/truo.exe`,
      },
    },
    // Scoop recalculates the hash from the release's SHA256SUMS on every new version,
    // so `scoop update` does not depend on this script running again.
    hash: {
      url: `https://github.com/${REPO}/releases/download/v$version/SHA256SUMS`,
      find: "([a-fA-F0-9]{64})\\s+truo-windows-x64\\.exe",
    },
  },
};
writeFileSync(resolve(OUT, "truo.json"), JSON.stringify(manifest, null, 2) + "\n", "utf8");

console.log(`dist-packagers/truo.rb    (brew, v${version})`);
console.log(`dist-packagers/truo.json  (scoop, v${version})`);
